Repository goldstar611/gitless, pull requests merged in 2022-02, with the labels that each got.

#3 Fix assumption that git workdir is relative to /.git/
  gitless/core.py
Labels: bug

#4 Fix issue https://github.com/gitless-vcs/gitless/issues/118
  gitless/core.py
Labels: bug

#8 Fix for issues https://github.com/gitless-vcs/gitless/issues/195
  gitless/core.py
  gitless/tests/test_core.py
Labels: bug

#19 Ask to create remote branch if not exists
  gitless/cli/gl_branch.py
Labels: enhancement

#21 Fixes https://github.com/goldstar611/gitless/issues/12
  gitless/cli/pprint.py
Labels: bug

#34 Improve gl pull and gl fetch
  gitless/cli/gl_fetch.py
  gitless/cli/gl_pull.py
  gitless/tests/test_e2e.py
Labels: enhancement, NeedsTest

#33 Adds gl patch, a wrapper for git format-patch
  gitless/cli/gl.py
  gitless/cli/gl_patch.py
Labels: enhancement, NeedsTest
